[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools', 'wheel']

[project]
name = 'pmi-lib'
version = '0.0.1'
description = 'PMI library - Group <group number>'
readme = 'README.md'
requires-python = '>=3.14'
license = 'MIT'
license-files = ['LICENSE.txt']
authors = [
  {name = 'Group member 1', email = 'member1@students.uu.nl'},
  {name = 'Group member 2', email = 'member2@students.uu.nl'},
  {name = 'Group member 3', email = 'member3@students.uu.nl'},
  {name = 'Group member 4', email = 'member4@students.uu.nl'},
]
dependencies = ["nibabel", "numpy", "pydicom"]
