project:
  type: book

  output-dir: ./_site

book:
  title: "Programming for Medical Imaging"
  author: "Image Sciences Institute<br>UMC Utrecht"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - part: "Week 1: Images"
      chapters: 
        - introduction.qmd
        - medical-images.ipynb
    - part: "Week 2: Scripting"
      chapters:
        - installation-and-setup.qmd
        - course-materials.qmd
        - scripting-variables-types.ipynb
        - scripting-data.ipynb
    - part: "Week 3: Functions"
      chapters:
        - functions-comparisons.ipynb
        - functions-iteration.ipynb
        - functions-functions.ipynb
    - part: "Week 4: Libraries"
      chapters:
        - programs-libraries.ipynb
    - part: "Week 5: Classes"
      chapters:
        - classes-objects.ipynb
    - part: "Week 6: Languages"
      chapters:
        - programming-languages.ipynb
    - part: "Week 7: Computation"
      chapters:
        - computation.ipynb
    - part: "Week 8: Q&A"
      chapters:
        - qa.ipynb
    - references.qmd
  repo-url: https://github.com/umcu-isi/programming-for-medical-imaging/
  repo-subdir: book
  issue-url: https://github.com/umcu-isi/programming-for-medical-imaging/issues/new
  repo-actions: [edit, issue, source]
  sidebar:
    logo: images/python-logo-pmi.png

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
