project:
  type: book

  output-dir: ./_site

book:
  title: "Programming for Medical Imaging"
  author: "Image Sciences Institute<br>UMC Utrecht"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - part: "Preparation"
      chapters: 
        - installation-and-setup.qmd
        - course-materials.qmd
    - part: "Week 1"
      chapters: 
        - introduction.qmd
        - medical-images.ipynb
    - part: "Week 2"
      chapters:
        - scripting.ipynb
    - part: "Week 3"
      chapters:
        - functions.ipynb
    - part: "Week 4"
      chapters:
        - programs-libraries.ipynb
    - part: "Week 5"
      chapters:
        - classes-objects.ipynb
    - part: "Week 6"
      chapters:
        - programming-languages.ipynb
    - part: "Week 7"
      chapters:
        - efficient-computation.ipynb
    - part: "Week 8"
      chapters:
        - qa.ipynb
    - references.qmd
  repo-url: https://github.com/umcu-isi/programming-for-medical-imaging/
  repo-subdir: book
  issue-url: https://github.com/umcu-isi/programming-for-medical-imaging/issues/new
  repo-actions: [edit, issue, source]
  sidebar:
    logo: images/python-logo-pmi.png

bibliography: references.bib

format:
  html:
    theme: cosmo
