# Welcome! {.unnumbered}

Welcome to the course book for the course *[Programming for Medical Imaging](https://mix.isi.uu.nl/courses/programming/)*. 

In the area of medical imaging, it is necessary to create computer programs to process and analyse image data. This course deals with both the theoretical knowledge and practical skills of working with (large) image datasets.

You will learn the basics of the file structures to store medical image data, and how to write source code and create a computer program to process medical images efficiently. This includes debugging, problem solving and maintenance of software.
 
The course includes algorithms and data structures used in medical image analysis. Modern programming languages are used, such as Python and C++, while paying attention to efficient computer instructions and memory usage.

This course follows the *flipped classroom* principle: courses are a combination of online material and exercises, with practical sessions under supervision at the UMC Utrecht.

---

The course material is licensed under a Creative Commons Attribution 4.0 International License. You can view the license on our [GitHub repository](https://github.com/umcu-isi/programming-for-medical-imaging).
