# Medical Images

This week, we will start with explaining different file formats to store (medical) images. There are many different formats for 2D images, each with their own specific pros and cons. Medical images are often multi-dimensional (3D, 3D-time, etc), which requires specific features to store all the information. In this course, we will use the DICOM (dcm) and Nifti (nii) formats.

Study the following sources at home to be prepared for the practicum on Friday. Then we will start playing around with all kind of images and tools.

1. General info on 2D image formats (14 min)\
   <https://www.youtube.com/watch?v=WblPwVq9KnU>
1. Article on medical image formats (7 pgs)\
   <https://pmc.ncbi.nlm.nih.gov/articles/PMC3948928/>
1. Visualisation of DICOM, focus on nifti (1 web page)\
   <https://medium.com/@hannah.hj.do/medical-image-and-visualization-b204e6a1b1d1>
1. Nice intro into DICOM (8 min)\
   <https://www.youtube.com/watch?v=B5F0zTbN_fk>
1. Advanced explanation of DICOM (21 min)\
   <https://www.youtube.com/watch?v=eLS9nDVJx5Y>

Install the following tools on your laptop:

::: {.panel-tabset}
## Windows
6. MicroDicom (Windows only)\
   <https://www.microdicom.com>

## macOS
6. Osirix Lite (macOS only)\
   <https://www.osirix-viewer.com/osirix/osirix-md/download-osirix-lite/>
:::

7. ITK-SNAP (Windows/macOS)\
   <https://www.itksnap.org/>
